### ISSUE TITLE
得物报错，加验证了

### ISSUE THREAD

**Issue by AfanChang** [q7q7q7q7q7q7q7/ziyou#10]
领取任务奖励失败! {'code': 485, 'msg': '请校验验证码', 'data': {'resultCode': 485, 'sessionId': 'o7Pf0eh01PgBngtMSQceSI4P6c7ppZxX3vMH5ucEUfyc7qIqFVkPu6NZD3yHWPsJkve6pmtv3xMIRQygKqlxqC', 'type': 2}, 'status': 485}
开始任务：完成五次浇灌
领取任务奖励失败! {'code': 485, 'msg': '请校验验证码', 'data': {'resultCode': 485, 'sessionId': 'OyS8kALzEpE7JM6ERzHmTSkN9Ln8E96fEgh1YBYn8YELMIAUwim5LB1rxZcTj4DO2E7hHAafZeKLyzkBDVtyw4', 'type': 2}, 'status': 485}
开始任务：收集一次水滴生产
领取任务奖励失败! {'code': 485, 'msg': '请校验验证码', 'data': {'resultCode': 485, 'sessionId': 'vmub7tECtJ8IoBPsJVlqTQ9WsWWLoB3bz2c8UX2g6DzfTkAuLhKSGZtfsIoNVQDZPdLJkuIkJ1jHm5pMDjcEfo', 'type': 2}, 'status': 485}

**Comment by q7q7q7q7q7q7q7** [comment]
已修复
