### ISSUE TITLE
关于得物脚本

### ISSUE THREAD

**Issue by AfanChang** [q7q7q7q7q7q7q7/ziyou#13]
在多账号环境下填其中一个ck的sk和ua来运行多个账号，会一直跳验证码，有没有办法多弄几个其他账号的sk和ua来运行脚本

**Comment by q7q7q7q7q7q7q7** [comment]
暂且搁置

**Comment by qq846511277** [comment]
你这多个账号，你多少个账号啊？你可以把脚本多复制几份，换多个不同的sk 和ua
