### ISSUE TITLE
得物有的任务不能执行了

### ISSUE THREAD

**Issue by zzyyyds88** [q7q7q7q7q7q7q7/ziyou#7]
★开始任务：浏览into you品牌页10s
该任务暂时无法处理，请提交日志给作者！ {'classify': 2, 'taskId': 'x69PK', 'taskName': '浏览into you品牌页10s', 'isComplete': False, 'isReceiveReward': False, 'taskType': 1, 'total': 1, 'priority': 4, 'jumpUrl': 'https://m.poizon.com/router/product/BrandDetailPage?brandId=1002406&source=xvyuanshu&gameName=&taskId=x69PK&gameTaskFlag=true&btd=31945&timeCount=10&taskType=1&countdownIcon=%7B%22countdownIcon%22%3A%22https%3A%2F%2Fcdn.poizon.com%2Fnode-common%2F28c7b3d4060e086551dcc84eca7bfbeb.png%22%2C%22hideCountdownIcon%22%3A%22https%3A%2F%2Fcdn.poizon.com%2Fnode-common%2Fa8b472c7622a53454d82745345cefa71.png%22%2C%22coordinate%22%3A%2212%2C600%22%7D&scrollbarColor=%2301C1C2&fontColor=%23FFFFFF', 'curStep': 0, 'countdownTime': 10, 'androidUrl': '', 'iosUrl': '', 'deskTopTitle': '', 'deskTopIcon': '', 'effectType': 2, 'rewardType': 1, 'rewardCount': 40, 'rewardRemark': '', 'isProcessing': False, 'btnName': '去完成', 'isLowVersion': False, 'isObtain': False, 'completeFlag': 0, 'reportBind': False, 'taskBgUrl': '', 'canJumpAfterFinished': Fal

**Comment by q7q7q7q7q7q7q7** [comment]
更新
